export const ADD_CLUB = "ADD_CLUB";
export const UPDATE_CLUB = "UPDATE_CLUB";
export const DESTROY_CLUB = "DESTROY_CLUB";
export const CLUB_FETCH_START = 'CLUB_FETCH_START';
export const CLUB_FETCH_COMPLETE = 'CLUB_FETCH_COMPLETE';
export const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
export const GET_CLUBS_FROM_DATABASE = 'GET_CLUBS_FROM_DATABASE';

export const CREATE_CONNECTION = "CREATE_CONNECTION";
export const DESTROY_CONNECTION = "DESTROY_CONNECTION";

export const CREATE_DB_CONNECTION = "CREATE_DB_CONNECTION";
export const DESTROY_DB_CONNECTION = "DESTROY_DB_CONNECTION";