export const CLUB_CREATE = "CLUB_CREATE";

export const INVITATION_CREATE ='INVITATION_CREATE';

export const PROPOSAL_CREATE ='PROPOSAL_CREATE';

export const EXCHANGE_CREATE = 'EXCHANGE_CREATE';

export const INDEX_CREATE = 'INDEX_CREATE';

export const STOCK_CREATE = 'STOCK_CREATE';

export const CREATE_CONNECTION = "CREATE_CONNECTION";
export const DESTROY_CONNECTION = "DESTROY_CONNECTION";

export const INITIALISE_DB = 'INITIALISE_DB';
export const CREATE_DB = "CREATE_DB";
export const GET_ALL_FROM_DB = 'GET_ALL_FROM_DB';
export const GET_ALL_FROM_SERVER = 'GET_ALL_FROM_SERVER';
export const TEAR_DOWN_DB = 'TEAR_DOWN_DB';
export const DESTROY_DB = "DESTROY_DB";