export const CLUB_CREATE = "CLUB_CREATE";

export const INVITATION_CREATE ='INVITATION_CREATE';

export const PROPOSAL_CREATE ='PROPOSAL_CREATE';

export const INDEX_CREATE = 'INDEX_CREATE';
export const GET_INDICES_FROM_SERVER = 'GET_INDICES_FROM_SERVER';

export const CREATE_CONNECTION = "CREATE_CONNECTION";
export const DESTROY_CONNECTION = "DESTROY_CONNECTION";

export const INITIALISE_DB = 'INITIALISE_DB';
export const SYNCHRONISE_STATE_WITH_DB = 'SYNCHRONISE_STATE_WITH_DB';
export const TEAR_DOWN_DB = 'TEAR_DOWN_DB';
export const CREATE_DB = "CREATE_DB";
export const DESTROY_DB = "DESTROY_DB";